POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvb2xjYXQiLCJpZCI6IjYxNzEzMjlmYTI3ZDBjM2FiM2IxNmU1OCIsImlhdCI6MTYzNDgyMTg0NH0.Emv5H3dm1jtatHMXIO3cNPJJv4A1Grs9RALDEwLJCGw

{
  "title": "Daring Fireball",
  "author": "John Gruber",
  "url": "https://daringfireball.net/",
  "likes": 0
}